### ISSUE TITLE
generate kubernetes yamls that make a serverless app

### ISSUE THREAD

**Issue by AmitKumarDas** [simplekube/idl-gen#2]
### Problem Statement
Refer #1 
This issue is to devise a way to generate Kubernetes yamls (custom &/ native) for a serverless application. End user might want to customise on top of these generated yamls before applying the same against the desired cluster. 

**Value Add**: _End user does not deal with operational tasks to run serverless on Kubernetes clusters. They deal with the minimal specifications required to run the same._ This betters the `Inner Dev Loop` experience.

**Note**: _A serverless application depends on resources like Deployment, Service, HPA, Ingress, Cert-Manager, setting of DNS entries, & more_

### End User Workflow
- End user crafts a yaml that provides customisations to generate manifests for the server less app
  - e.g. image, values, etc. that fits up the app requirements
- End user feeds this yaml to a binary
  - Binary merges this yaml against a pre-configured serverless configuration
  - Binary generates a final set of yamls
  - Binary can optionally generate the dependencies of a server less app
    - e.g. CRDs, controller yamls
- End user applies these yamls against the cluster

**Comment by AmitKumarDas** [comment]
### Design Thoughts
#### Knative as the server less provider
- Delegate the entire functionality to [Knative](https://knative.dev/docs/)
- Following is the yaml that end user will deal with
```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name:
  annotations: # [optional] may be used to generate various configurations / settings
    generate.idl-gen/prehook-checks: "true"
    generate.idl-gen/posthook-checks: "true"
    generate.idl-gen/dependencies: "true"
spec:
```
